production:
  deny_delete: false
  auto_create: false
  force_repository: false
  post_create: /home/redmine/bin/redmine/post-create.sh
  max_repos: 0
  only_creator: false
  allow_add_local: false
  allow_pickup: false
  svn:
    path: {{SVN_PATH}}
    svnadmin: /usr/bin/svnadmin
    url: {{SVN_URL}}
  git:
    path: {{GIT_PATH}}
    git: /usr/bin/git
    options: --bare
    url: {{GIT_URL}}
    update_server_info: true
    git_ext: {{GIT_EXT}}
    append: trunk
